reference_access:
  check_direct_ref_nodes: true
_core:
  default_config_hash: 5WgHUWiUyFT1NXME3WlDnpiqnw8RK9BE5RDDKw-jEbo
check_content_types:
  group: group
  article: 0
  page: 0
check_direct_ref_nodes: 1
check_indirect_ref_nodes: 0
